### ISSUE TITLE
No linting is going on

### ISSUE THREAD

**Issue by jkmacy** [francis36012/linter-kotlin#1]
The supposed error catching isn't working, could something be wrong with the coffeescript file for it in lib?

**Comment by francis36012** [comment]
Thanks for reporting this. The problem is due to the casing used for the `grammarScope` entry in `init.coffee` (must match the `scopeName` in the language definition package), and the regex for matching errors and warnings.

This should be fixed in about 2 hours.

**Comment by francis36012** [comment]
@jkmacy Update `language-kotlin` and `linter-kotlin` packages to their respective latest versions; the linter should work after that.
