### ISSUE TITLE
Plugin Doesn't Work In Atom 1.16.0

### ISSUE THREAD

**Issue by napperley** [francis36012/linter-kotlin#3]
Started up Atom after its update to **v1.16.0** (via Deb package install in Linux Mint 17.3) and found that the **linter-kotlin** plugin isn't working. See the following screenshot:

![broken kotlin linter in atom 1 16 0](https://cloud.githubusercontent.com/assets/3538279/26093750/42fad090-3a6b-11e7-9566-99dd19756bfb.png)

Changing the Kotlin compiler path to a different location (not the default one) results in a mysterious error message appearing in Atom.

**Comment by francis36012** [comment]
Since the code is correct Kotlin code, you won't see any errors or warnings from the plugin. Can you please paste the error that results from changing the path to the compiler here.

**Comment by francis36012** [comment]
Hey @napperley, I published a new version of the package. Please update and see whether your issue has been fixed.

**Comment by napperley** [comment]
Thank you for publishing a new version of the plugin. The issue has been resolved, see the screenshot below:

![kotlin linter in atom 1 16 0](https://cloud.githubusercontent.com/assets/3538279/26134007/a0278cc4-3aff-11e7-9626-9eefc056b928.png)


Appears as though Atom uses a new UI for code linting. Does the **linter-kotlin** plugin display warnings and other general information reported by the Kotlin compiler?

**Comment by francis36012** [comment]
There are some messages that are shown when using JetBrains' IDEs due to lints (not available in the standard compiler) ran against your code. Are those the types of messages you are referring to in your comment above?

**Comment by napperley** [comment]
Didn't refer to the IDE ones. Just the Kotlin compiler.

**Comment by francis36012** [comment]
All errors and warnings reported by the compiler are given to the `atom-linter` package to be rendered
